
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Eustaquio
 */
public class Menu extends javax.swing.JFrame {

    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        menuAddPnl = new javax.swing.JPanel();
        menuAddLabel = new javax.swing.JLabel();
        menuAssignPnl = new javax.swing.JPanel();
        menuAssignLabel = new javax.swing.JLabel();
        menuPrintPnl = new javax.swing.JPanel();
        menuPrintlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(49, 11, 80));

        menuLabel.setBackground(java.awt.Color.red);
        menuLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        menuLabel.setForeground(java.awt.Color.red);
        menuLabel.setText("Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(menuLabel)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(menuLabel)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(76, 17, 123));

        menuAddPnl.setBackground(new java.awt.Color(76, 17, 123));
        menuAddPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 11, 80), 2));
        menuAddPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAddPnlMouseClicked(evt);
            }
        });

        menuAddLabel.setBackground(java.awt.Color.white);
        menuAddLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuAddLabel.setForeground(java.awt.Color.white);
        menuAddLabel.setText("Add");

        javax.swing.GroupLayout menuAddPnlLayout = new javax.swing.GroupLayout(menuAddPnl);
        menuAddPnl.setLayout(menuAddPnlLayout);
        menuAddPnlLayout.setHorizontalGroup(
            menuAddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAddPnlLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(menuAddLabel)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        menuAddPnlLayout.setVerticalGroup(
            menuAddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuAddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        menuAssignPnl.setBackground(new java.awt.Color(76, 17, 123));
        menuAssignPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 11, 80), 2));
        menuAssignPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAssignPnlMouseClicked(evt);
            }
        });

        menuAssignLabel.setBackground(java.awt.Color.white);
        menuAssignLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuAssignLabel.setForeground(java.awt.Color.white);
        menuAssignLabel.setText("Assign");

        javax.swing.GroupLayout menuAssignPnlLayout = new javax.swing.GroupLayout(menuAssignPnl);
        menuAssignPnl.setLayout(menuAssignPnlLayout);
        menuAssignPnlLayout.setHorizontalGroup(
            menuAssignPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAssignPnlLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(menuAssignLabel)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        menuAssignPnlLayout.setVerticalGroup(
            menuAssignPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuAssignLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        menuPrintPnl.setBackground(new java.awt.Color(76, 17, 123));
        menuPrintPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 11, 80), 2));
        menuPrintPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPrintPnlMouseClicked(evt);
            }
        });

        menuPrintlabel.setBackground(java.awt.Color.white);
        menuPrintlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuPrintlabel.setForeground(java.awt.Color.white);
        menuPrintlabel.setText("Print");

        javax.swing.GroupLayout menuPrintPnlLayout = new javax.swing.GroupLayout(menuPrintPnl);
        menuPrintPnl.setLayout(menuPrintPnlLayout);
        menuPrintPnlLayout.setHorizontalGroup(
            menuPrintPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrintPnlLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(menuPrintlabel)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        menuPrintPnlLayout.setVerticalGroup(
            menuPrintPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPrintlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuPrintPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuAddPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuAssignPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(menuAddPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(menuAssignPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(menuPrintPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuAddPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAddPnlMouseClicked
        AddScreen add = new AddScreen();
        add.show();
        this.dispose();
    }//GEN-LAST:event_menuAddPnlMouseClicked

    private void menuPrintPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPrintPnlMouseClicked
        PrintScreen print = new PrintScreen();
        print.show();
        this.dispose();
    }//GEN-LAST:event_menuPrintPnlMouseClicked

    private void menuAssignPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAssignPnlMouseClicked
        AssignScreen assign = new AssignScreen();
        assign.show();
        this.dispose();
    }//GEN-LAST:event_menuAssignPnlMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel menuAddLabel;
    private javax.swing.JPanel menuAddPnl;
    private javax.swing.JLabel menuAssignLabel;
    private javax.swing.JPanel menuAssignPnl;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JPanel menuPrintPnl;
    private javax.swing.JLabel menuPrintlabel;
    // End of variables declaration//GEN-END:variables
}
