/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Eustaquio
 */
public class PrintScreen extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public PrintScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        backBtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        prntCustomerBtn = new javax.swing.JPanel();
        prntCustomerLabel = new javax.swing.JLabel();
        prntBookingsBtn = new javax.swing.JPanel();
        prntBookingsLabel = new javax.swing.JLabel();
        prntPropertiesBtn = new javax.swing.JPanel();
        prntPropertiesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(49, 11, 80));

        jLabel4.setBackground(java.awt.Color.red);
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(java.awt.Color.red);
        jLabel4.setText("Print");

        backBtn.setBackground(java.awt.Color.white);
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        backBtn.setForeground(java.awt.Color.white);
        backBtn.setText("<");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(backBtn)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabel4)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(76, 17, 123));

        prntCustomerBtn.setBackground(new java.awt.Color(76, 17, 123));
        prntCustomerBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 11, 80), 2));
        prntCustomerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prntCustomerBtnMouseClicked(evt);
            }
        });

        prntCustomerLabel.setBackground(java.awt.Color.white);
        prntCustomerLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        prntCustomerLabel.setForeground(java.awt.Color.white);
        prntCustomerLabel.setText("Customer");

        javax.swing.GroupLayout prntCustomerBtnLayout = new javax.swing.GroupLayout(prntCustomerBtn);
        prntCustomerBtn.setLayout(prntCustomerBtnLayout);
        prntCustomerBtnLayout.setHorizontalGroup(
            prntCustomerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prntCustomerBtnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(prntCustomerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prntCustomerBtnLayout.setVerticalGroup(
            prntCustomerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prntCustomerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        prntBookingsBtn.setBackground(new java.awt.Color(76, 17, 123));
        prntBookingsBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 11, 80), 2));
        prntBookingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prntBookingsBtnMouseClicked(evt);
            }
        });

        prntBookingsLabel.setBackground(java.awt.Color.white);
        prntBookingsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        prntBookingsLabel.setForeground(java.awt.Color.white);
        prntBookingsLabel.setText("Bookings");

        javax.swing.GroupLayout prntBookingsBtnLayout = new javax.swing.GroupLayout(prntBookingsBtn);
        prntBookingsBtn.setLayout(prntBookingsBtnLayout);
        prntBookingsBtnLayout.setHorizontalGroup(
            prntBookingsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prntBookingsBtnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(prntBookingsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prntBookingsBtnLayout.setVerticalGroup(
            prntBookingsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prntBookingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        prntPropertiesBtn.setBackground(new java.awt.Color(76, 17, 123));
        prntPropertiesBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 11, 80), 2));
        prntPropertiesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prntPropertiesBtnMouseClicked(evt);
            }
        });

        prntPropertiesLabel.setBackground(java.awt.Color.white);
        prntPropertiesLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        prntPropertiesLabel.setForeground(java.awt.Color.white);
        prntPropertiesLabel.setText("Properties");

        javax.swing.GroupLayout prntPropertiesBtnLayout = new javax.swing.GroupLayout(prntPropertiesBtn);
        prntPropertiesBtn.setLayout(prntPropertiesBtnLayout);
        prntPropertiesBtnLayout.setHorizontalGroup(
            prntPropertiesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prntPropertiesBtnLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(prntPropertiesLabel)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        prntPropertiesBtnLayout.setVerticalGroup(
            prntPropertiesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prntPropertiesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prntBookingsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prntCustomerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prntPropertiesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(prntCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(prntBookingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(prntPropertiesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prntCustomerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prntCustomerBtnMouseClicked
       PrintCustomer customer = new PrintCustomer();
       customer.show();
       this.dispose();
    }//GEN-LAST:event_prntCustomerBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        Menu main = new Menu();
        main.show();
        this.dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    private void prntBookingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prntBookingsBtnMouseClicked
        PrintBookings bookings = new PrintBookings();
        bookings.show();
        this.dispose();
    }//GEN-LAST:event_prntBookingsBtnMouseClicked

    private void prntPropertiesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prntPropertiesBtnMouseClicked
        PrintProperties properties = new PrintProperties();
        properties.show();
        this.dispose();
    }//GEN-LAST:event_prntPropertiesBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel prntBookingsBtn;
    private javax.swing.JLabel prntBookingsLabel;
    private javax.swing.JPanel prntCustomerBtn;
    private javax.swing.JLabel prntCustomerLabel;
    private javax.swing.JPanel prntPropertiesBtn;
    private javax.swing.JLabel prntPropertiesLabel;
    // End of variables declaration//GEN-END:variables
}
